FROM alpine:3.8

# This Dockerfile just creates a folder. The actual binary has to be compiled and linked separately by mounting a volume.
# Intended for development only.

RUN apk --no-cache add ca-certificates=20190108-r0 libc6-compat=1.1.19-r11
RUN mkdir /app

EXPOSE 9091
